### ISSUE TITLE
chore: Review Studio UX for Usability and Brand

### ISSUE THREAD

**Issue by dthyresson** [redwoodjs/studio#31]
Overall, there UX for Studio could use a review to make it easier to find, view, and manage information.

Examples:

* pagination
* more filtering options for searches (date ranges, aggregation levels)
* info architecture
* and more

In addition, we might consider some branding as Studio rolls out.

Do we leverage the "Bighorn" branding color schema in:

![image](https://github.com/redwoodjs/studio/assets/1051633/5550ffb2-6b58-487c-9a3d-e0441eb57624)

```js
colors: {
        licorice: '#181311' /* dark brown */,
        sulu: '#c4f482' /* lime green */,
        maiTai: '#a86338' /* tan */,
        battleshipGray: '#828282' /* gray */,
        darkPastelRed: '#bf4722' /* redwood red */,
        labels: {
          soon: { text: '#5D960C', bg: '#dcf8b4' } /* green */,
          later: { text: '#944711', bg: '#F1AB78' } /* orange */,
          done: { text: '#513C51', bg: '#B097B2' } /* purple */,
          planned: { text: '#477185', bg: '#BCD1DB' } /* blue */,
        },
        white: '#ffffff',
        black: '#000000',
      },
```

For example?

**Comment by ahaywood** [comment]
I'd love to put some time and attention into the overall branding and styling of Studio (post Bighorn v0.1 release).

My initial thoughts: I'm concerned with changing the studio color palette to match the new Bighorn site because it leans leans heavily into browns, CTAs are a lime green, and there's a touch of red that I'm pulling in from the RedwodJS logo. This is fine for a marketing site, but from a product perspective can cause problems:

- Browns could feel dull and muddy, especially when dealing with data
- Lime green and red can interfere with state (success and error messaging)

**Comment by dthyresson** [comment]
I went purple! https://github.com/redwoodjs/studio/pull/35
